### ISSUE TITLE
请教关于代码的问题

### ISSUE THREAD

**Issue by leader120** [Zhangzhk0819/GNN-Embedding-Leaks#2]
大佬您好！我在运行您的代码时候，出现很多包不存在，比如：

from lib_classifier.nn_structure.mlp_net import MLPNet

from dispatcher_shell import DispatcherShell等库函数，以及缺少一些文件

(leader) [leader@node1 GNN-Embedding-Leaks-main]$ python main.py 
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main(args, args['exp'])
  File "main.py", line 38, in main
    config_logger(logger_name)
  File "main.py", line 29, in config_logger
    fh1 = logging.FileHandler(config.LOG_PATH + save_name + '.txt', 'w')
  File "/home/leader/anaconda3/envs/leader/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/leader/anaconda3/envs/leader/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disk0/project/GNN-Embedding-Leaks-main/temp_data/log/txt/graph_recon_AIDS_mincut_pool_mincut_pool_4.txt'
请问一下这个怎么解决

**Comment by Sylvia-HY** [comment]
请问您解决了吗？我也找不到from dispatcher_shell import DispatcherShell。

**Comment by leader120** [comment]
我记得我直接注释掉了，然后自己写了一个分类器就搞定了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhangzhk0819/GNN-Embedding-Leaks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zhangzhk0819/GNN-Embedding-Leaks] 请教关于代码的问题 (Issue #2)





 
请问您解决了吗？我也找不到from dispatcher_shell import DispatcherShell。

**Comment by Sylvia-HY** [comment]
嗯嗯好的，不知道您是否方便分享下源码？如果不方便的话，非常抱歉打扰到您。

**Comment by leader120** [comment]
我晚上回去找找，找到了发给你，他那个代码跑起来也挺费时间的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhangzhk0819/GNN-Embedding-Leaks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zhangzhk0819/GNN-Embedding-Leaks] 请教关于代码的问题 (Issue #2)





 
嗯嗯好的，不知道您是否方便分享下源码？如果不方便的话，非常抱歉打扰到您。

**Comment by Sylvia-HY** [comment]
> 我晚上回去找人，找到了给你，他那个代码运行起来也费时间
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Zhangzhk0819/GNN -嵌入泄漏” ***@***.***>；发送时间:2024年5月28日(星期二) 下午3:26 ***@***.***>; ***@***.******@***.***>;主题: Re: [Zhangzhk0819/GNN-Embedding-Leaks] 请教关于代码问题 (Issue #2 ) 嗯嗯好的，不知道您方便分享下源码？否则方便的话，非常抱歉打扰到您。 — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：***@***.***>

嗯嗯好的，我的邮箱是yahan9979@gmail.com，十分感谢！！！

**Comment by Sylvia-HY** [comment]
> 我晚上回去找找，找到了发给你，他那个代码跑起来也挺费时间的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhangzhk0819/GNN-Embedding-Leaks" ***@***.***&gt;; 发送时间:&nbsp;2024年5月28日(星期二) 下午3:26 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Zhangzhk0819/GNN-Embedding-Leaks] 请教关于代码的问题 (Issue #2) 嗯嗯好的，不知道您是否方便分享下源码？如果不方便的话，非常抱歉打扰到您。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

冒昧打扰，请问您找到了吗？
